name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  build:
    name: Gerar e publicar a cobrinha
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Checkout do repositÃ³rio
        uses: actions/checkout@v4

      - name: ğŸ Gerar animaÃ§Ã£o da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: reinaldo-matheus
          outputs: dist/github-contribution-grid-snake.svg

      - name: ğŸš€ Publicar arquivo no branch output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout --orphan output
          git reset
          mv dist/github-contribution-grid-snake.svg .
          git add github-contribution-grid-snake.svg
          git commit -m "ğŸ AtualizaÃ§Ã£o automÃ¡tica da cobrinha"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/reinaldo-matheus/reinaldo-matheus.git output
