name: Generate Custom Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Gerar e publicar animaÃ§Ã£o da cobrinha personalizada
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Checkout do repositÃ³rio
        uses: actions/checkout@v4

      - name: ğŸ Gerar animaÃ§Ãµes (modo claro e escuro personalizados)
        uses: Platane/snk@v3
        with:
          github_user_name: reinaldo-matheus
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=blue-violet
            dist/github-contribution-grid-snake-dark.svg?palette=tokyo-night

      - name: ğŸš€ Publicar no branch output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout --orphan output
          git reset
          mv dist/* .
          git add .
          git commit -m "ğŸ AtualizaÃ§Ã£o automÃ¡tica da cobrinha estilizada (Tokyo Night)"
          git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/reinaldo-matheus/reinaldo-matheus.git output


